### ISSUE TITLE
Exception Thrown when Toggling Structure State during Turn Update

### ISSUE THREAD

**Issue by Ragora** [OuterDeepSpace/OuterDeepSpace#24]
Looks like the game can throw an exception when you're toggling structure states at the same exact moment that the game is going to update for a turn. There's probably other similar timing issues.
## 2016-03-25 17:49:20 WAR -- OSCI Exception in event loop

Traceback (most recent call last):
  File "../libs/client/osci/main.py", line 309, in <module>
    evt = app.processEvent(evt)
  File "../libs/client/pygameui/Application.py", line 146, in processEvent
    return self.focusedWindow.processMB1Up(evt)
  File "../libs/client/pygameui/Window.py", line 119, in processMB1Up
    return MetaWidget.processMB1Up(self, evt)
  File "../libs/client/pygameui/MetaWidget.py", line 171, in processMB1Up
    return widget.processMB1Up(evt)
  File "../libs/client/pygameui/Button.py", line 58, in processMB1Up
    self.processAction(self.action)
  File "../libs/client/pygameui/Widget.py", line 91, in processAction
    self.parent.processAction(actionName, data, widget)
  File "../libs/client/pygameui/Widget.py", line 89, in processAction
    apply(handler, (widget, actionName, data))
  File "../libs/client/osci/dialog/StarSystemDlg.py", line 948, in onSwitchStructOnOff
    not struct[STRUCT_IDX_STATUS] & STRUCT_STATUS_ON)
## TypeError: list indices must be integers, not NoneType

2016-03-25 17:49:20 DBG -- Processing exception

**Comment by Ragora** [comment]
Looking at just the exception, it looks like STRUCT_IDX_STATUS is assigned to None at the start of a turn flip. There's probably a lot of state variables we want to hold on to throughout the turn flipping unless explicitly reassigned.
